/**
 * The Medora AI pipeline.
 *
 *   user input
 *     → intent detection
 *     → structured extraction
 *     → provider selection
 *     → retrieval
 *     → safety validation
 *     → response + provenance
 *     → feedback (collected in the UI, attached by envelope id)
 *
 * Every stage is recorded in `envelope.trace` so the interface can show what
 * actually happened instead of implying a black box.
 */
import { detectIntent, intentLabels, type IntentResult } from "./intent";
import type {
  PatientSummaryRequest,
  ProviderOutput,
  TriageRequest,
} from "./provider-types";
import { resolveProvider, capabilityLabels } from "./registry";
import { BLOCKED_COPY, detectRedFlags, validate } from "./safety";
import type {
  AiCapability,
  AiConfidence,
  AiEnvelope,
  AiPayload,
  AiSource,
  PipelineStage,
} from "./schemas";

const uid = () => `ai_${Math.random().toString(36).slice(2, 10)}`;

const confidenceFrom = (
  matchScore: number,
  intentScore: number,
  rationale: string,
): AiConfidence => {
  const score = Number((matchScore * 0.7 + intentScore * 0.3).toFixed(2));
  const level: AiConfidence["level"] =
    score >= 0.8
      ? "high"
      : score >= 0.6
        ? "moderate"
        : score >= 0.35
          ? "low"
          : "unverified";
  return { level, score, rationale };
};

interface Timer {
  stages: PipelineStage[];
  mark: (
    name: PipelineStage["name"],
    label: string,
    status: PipelineStage["status"],
    detail: string,
  ) => void;
}

const timer = (): Timer => {
  let last = Date.now();
  const stages: PipelineStage[] = [];
  return {
    stages,
    mark: (name, label, status, detail) => {
      const now = Date.now();
      stages.push({ name, label, status, detail, ms: now - last });
      last = now;
    },
  };
};

const EMERGENCY_SOURCE: AiSource = {
  id: "policy:red-flag-routing",
  label: "Medora red-flag routing",
  detail:
    "A fixed emergency term list. The wording below is written by Medora, never generated by a model.",
  kind: "policy",
  verified: true,
};

function escalationEnvelope(
  capability: AiCapability,
  redFlags: string[],
  trace: PipelineStage[],
): AiEnvelope {
  const payload: AiPayload = {
    kind: "escalation",
    headline: "This needs urgent professional care",
    body: `Your message mentions ${redFlags.join(", ")}. Medora cannot assess emergencies and will not try. Contact your local emergency number or go to the nearest emergency department now.`,
    triggeredBy: redFlags,
    action:
      "Call emergency services. Do not wait for an answer from this assistant.",
  };
  return {
    id: uid(),
    capability,
    createdAt: new Date().toISOString(),
    providerId: "medora-policy",
    providerLabel: "Medora safety policy",
    mode: "demo",
    simulated: false,
    payload,
    confidence: {
      level: "high",
      score: 0.99,
      rationale: "Deterministic red-flag rule; no model involved.",
    },
    sources: [EMERGENCY_SOURCE],
    safety: {
      passed: true,
      rulesRun: ["Red-flag term routing"],
      violations: [],
      redFlags,
      escalate: true,
      notice: "Routed to emergency guidance before any content was generated.",
    },
    followUps: [],
    trace,
  };
}

function wrap<T extends AiPayload>(
  capability: AiCapability,
  provider: { id: string; label: string; mode: "demo" | "live" },
  output: ProviderOutput<T>,
  intent: { confidence: number },
  userText: string,
  trace: PipelineStage[],
): AiEnvelope {
  const safety = validate({
    payload: output.payload,
    sources: output.sources,
    userText,
  });
  const blocked = !safety.passed;

  const payload: AiPayload = blocked
    ? {
        kind: "unavailable",
        headline: BLOCKED_COPY.headline,
        body: `${BLOCKED_COPY.body} Failed checks: ${safety.violations.join(" ")}`,
        missingCapability: capability,
        whatALiveProviderWouldDo:
          "A connected provider must pass the same validator before its output is shown.",
      }
    : output.payload;

  return {
    id: uid(),
    capability,
    createdAt: new Date().toISOString(),
    providerId: provider.id,
    providerLabel: provider.label,
    mode: provider.mode,
    simulated: provider.mode === "demo",
    payload,
    confidence: blocked
      ? {
          level: "unverified",
          score: 0,
          rationale: "Response blocked by the safety validator.",
        }
      : confidenceFrom(
          output.matchScore,
          intent.confidence,
          output.matchRationale,
        ),
    sources: output.sources,
    safety,
    followUps: blocked ? [] : (output.followUps ?? []),
    trace,
  };
}

function unavailable(
  capability: AiCapability,
  headline: string,
  body: string,
  whatALiveProviderWouldDo: string,
  trace: PipelineStage[],
): AiEnvelope {
  return {
    id: uid(),
    capability,
    createdAt: new Date().toISOString(),
    providerId: "medora-demo",
    providerLabel: "Medora demo adapter",
    mode: "demo",
    simulated: true,
    payload: {
      kind: "unavailable",
      headline,
      body,
      missingCapability: capability,
      whatALiveProviderWouldDo,
    },
    confidence: {
      level: "unverified",
      score: 0,
      rationale: "No connected provider could serve this request.",
    },
    sources: [
      {
        id: `policy:unavailable:${capability}`,
        label: "Integration not connected",
        detail: whatALiveProviderWouldDo,
        kind: "policy",
        verified: true,
      },
    ],
    safety: {
      passed: true,
      rulesRun: ["Refuse rather than generate"],
      violations: [],
      redFlags: [],
      escalate: false,
      notice: "Nothing was generated, so nothing needed validating.",
    },
    followUps: [],
    trace,
  };
}

/* ------------------------------ Entry points ------------------------------ */

/** Free-text assistant entry point: runs the full pipeline. */
export async function runAssistantPipeline(
  question: string,
): Promise<AiEnvelope> {
  const t = timer();

  const redFlags = detectRedFlags(question);
  const intent: IntentResult = detectIntent(question);
  t.mark(
    "intent_detection",
    "Intent detection",
    "ok",
    `${intentLabels[intent.intent]} (${Math.round(intent.confidence * 100)}%)${
      intent.matchedSignals.length ? ` · ${intent.matchedSignals[0]}` : ""
    }`,
  );

  const e = intent.entities;
  t.mark(
    "entity_extraction",
    "Structured extraction",
    "ok",
    [
      e.medicineNames.length
        ? `medicines: ${e.medicineNames.join(", ")}`
        : null,
      e.strength ? `strength: ${e.strength}` : null,
      e.form ? `form: ${e.form}` : null,
      e.symptoms.length ? `symptoms: ${e.symptoms.join(", ")}` : null,
    ]
      .filter(Boolean)
      .join(" · ") || "No structured entities found in the message.",
  );

  if (redFlags.length) {
    t.mark(
      "provider_selection",
      "Provider selection",
      "skipped",
      "Emergency routing bypasses all providers.",
    );
    t.mark(
      "retrieval",
      "Retrieval",
      "skipped",
      "No retrieval is performed for red-flag messages.",
    );
    t.mark(
      "safety_validation",
      "Safety validation",
      "ok",
      `Red flags matched: ${redFlags.join(", ")}`,
    );
    t.mark(
      "response_composition",
      "Response",
      "ok",
      "Fixed emergency copy returned.",
    );
    return escalationEnvelope(intent.capability, redFlags, t.stages);
  }

  const provider = resolveProvider(intent.capability);
  t.mark(
    "provider_selection",
    "Provider selection",
    "ok",
    `${provider.label} · ${provider.mode === "live" ? "live provider" : "demo adapter (simulated)"} for ${capabilityLabels[intent.capability]}`,
  );

  if (intent.intent === "price_or_stock") {
    t.mark(
      "retrieval",
      "Retrieval",
      "blocked",
      "Prices and stock are never answered by the AI layer.",
    );
    t.mark(
      "safety_validation",
      "Safety validation",
      "ok",
      "Refusal path — nothing generated.",
    );
    t.mark(
      "response_composition",
      "Response",
      "ok",
      "Directed to the verified price comparison screens.",
    );
    return unavailable(
      "medicine_intelligence",
      "Prices and stock don't come from the assistant",
      "Medora's assistant is not allowed to state a price or say whether a pharmacy has stock. Those numbers only ever come from the verified pharmacy price feed shown on the comparison and pharmacy screens, with the pharmacy and update time attached.",
      "A connected pharmacy price feed publishes prices and availability with a timestamp per listing.",
      t.stages,
    );
  }

  let output: ProviderOutput<AiPayload> | null = null;

  if (intent.intent === "medicine_explanation") {
    output = (await provider.explainMedicine(
      question,
    )) as ProviderOutput<AiPayload> | null;
  } else if (intent.intent === "medicine_comparison") {
    const stopWords = new Set([
      "compare",
      "vs",
      "versus",
      "and",
      "between",
      "difference",
      "differences",
      "which",
      "better",
      "is",
      "the",
      "what",
      "how",
      "does",
      "differ",
      "from",
    ]);
    const rawTokens = question
      .replace(/[^\w\s]/g, " ")
      .split(/\s+/)
      .filter((w) => w.length > 2 && !stopWords.has(w.toLowerCase()));
    const comparisonList =
      e.medicineIds.length > 0
        ? e.medicineIds
        : e.medicineNames.length > 0
          ? e.medicineNames
          : rawTokens;
    output = (await provider.compareMedicines(
      comparisonList.length >= 1
        ? comparisonList
        : ["paracetamol", "ibuprofen"],
    )) as ProviderOutput<AiPayload> | null;
  } else if (
    intent.intent === "interaction_check" ||
    intent.intent === "allergy_check"
  ) {
    const medList =
      e.medicineNames.length > 0
        ? e.medicineNames
        : question
            .replace(/[^\w\s]/g, " ")
            .split(/\s+/)
            .filter((w) => w.length > 3);
    output = (await provider.checkInteractions(
      medList,
      [],
    )) as ProviderOutput<AiPayload>;
  } else if (intent.intent === "symptom_triage") {
    output = (await provider.triage({
      symptoms: e.symptoms.length > 0 ? e.symptoms : [question],
      freeText: question,
      durationDays: e.durationDays ?? 3,
      severity: 4,
      currentMedicines: [],
      allergies: [],
      selectedRedFlags: [],
    })) as ProviderOutput<AiPayload>;
  } else if (intent.intent === "lab_explanation") {
    output = (await provider.explainLabReport(
      question,
    )) as ProviderOutput<AiPayload> | null;
  } else if (intent.intent === "medicine_search") {
    output = (await provider.interpretSearch(
      question,
    )) as ProviderOutput<AiPayload>;
  }

  if (!output) {
    output = (await provider.answerInformational(
      question,
    )) as ProviderOutput<AiPayload>;
    t.mark(
      "retrieval",
      "Retrieval",
      "ok",
      "No specific record matched; fell back to the honest no-answer path.",
    );
  } else {
    t.mark("retrieval", "Retrieval", "ok", output.matchRationale);
  }

  const envelope = wrap(
    intent.capability,
    provider,
    output,
    intent,
    question,
    t.stages,
  );
  t.mark(
    "safety_validation",
    "Safety validation",
    envelope.safety.passed ? "ok" : "blocked",
    envelope.safety.passed
      ? envelope.safety.notice
      : envelope.safety.violations.join(" "),
  );
  t.mark(
    "response_composition",
    "Response & provenance",
    "ok",
    `${envelope.sources.length} source chip(s) attached · confidence ${envelope.confidence.level}`,
  );
  return { ...envelope, trace: t.stages };
}

/* Direct capability entry points used by the non-chat screens. */

export async function runTriagePipeline(
  request: TriageRequest,
): Promise<AiEnvelope> {
  const t = timer();
  const provider = resolveProvider("symptom_triage");
  t.mark(
    "intent_detection",
    "Intent detection",
    "skipped",
    "Structured triage form — intent is known.",
  );
  t.mark(
    "entity_extraction",
    "Structured extraction",
    "ok",
    `${request.symptoms.length} symptom(s), severity ${request.severity}/10.`,
  );
  t.mark(
    "provider_selection",
    "Provider selection",
    "ok",
    `${provider.label} · ${provider.mode}`,
  );
  const output = await provider.triage(request);
  t.mark("retrieval", "Retrieval", "ok", output.matchRationale);
  const envelope = wrap(
    "symptom_triage",
    provider,
    output,
    { confidence: 0.9 },
    request.freeText,
    t.stages,
  );
  t.mark(
    "safety_validation",
    "Safety validation",
    envelope.safety.passed ? "ok" : "blocked",
    envelope.safety.notice,
  );
  t.mark(
    "response_composition",
    "Response & provenance",
    "ok",
    `${envelope.sources.length} source chip(s) attached.`,
  );
  return { ...envelope, trace: t.stages };
}

export async function runInteractionPipeline(
  medicines: string[],
  allergies: string[],
): Promise<AiEnvelope> {
  const t = timer();
  const provider = resolveProvider("drug_interaction");
  t.mark(
    "intent_detection",
    "Intent detection",
    "skipped",
    "Structured interaction check.",
  );
  t.mark(
    "entity_extraction",
    "Structured extraction",
    "ok",
    `${medicines.length} medicine(s), ${allergies.length} allergy record(s).`,
  );
  t.mark(
    "provider_selection",
    "Provider selection",
    "ok",
    `${provider.label} · ${provider.mode}`,
  );
  const output = await provider.checkInteractions(medicines, allergies);
  t.mark("retrieval", "Retrieval", "ok", output.matchRationale);
  const envelope = wrap(
    "drug_interaction",
    provider,
    output,
    { confidence: 0.9 },
    medicines.join(" "),
    t.stages,
  );
  t.mark(
    "safety_validation",
    "Safety validation",
    "ok",
    envelope.safety.notice,
  );
  t.mark(
    "response_composition",
    "Response & provenance",
    "ok",
    "Findings limited to what can be proven.",
  );
  return { ...envelope, trace: t.stages };
}

export async function runPatientSummaryPipeline(
  request: PatientSummaryRequest,
): Promise<AiEnvelope> {
  const t = timer();
  const provider = resolveProvider("patient_summary");
  t.mark(
    "intent_detection",
    "Intent detection",
    "skipped",
    "Structured summary request.",
  );
  t.mark(
    "entity_extraction",
    "Structured extraction",
    "ok",
    `${request.currentMedicines.length} current medicine(s).`,
  );
  t.mark(
    "provider_selection",
    "Provider selection",
    "ok",
    `${provider.label} · ${provider.mode}`,
  );
  const output = await provider.summarisePatient(request);
  t.mark("retrieval", "Retrieval", "ok", output.matchRationale);
  const envelope = wrap(
    "patient_summary",
    provider,
    output,
    { confidence: 0.9 },
    "",
    t.stages,
  );
  t.mark(
    "safety_validation",
    "Safety validation",
    "ok",
    envelope.safety.notice,
  );
  t.mark(
    "response_composition",
    "Response & provenance",
    "ok",
    "Composed from your own entries only.",
  );
  return { ...envelope, trace: t.stages };
}
