/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SwitchRouteImport } from './routes/switch'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminPharmaciesRouteImport } from './routes/admin.pharmacies'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiScanBottleRouteImport } from './routes/api.scan-bottle'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppCartRouteImport } from './routes/app.cart'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppInteractionsRouteImport } from './routes/app.interactions'
import { Route as AppLabsRouteImport } from './routes/app.labs'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppPharmaciesRouteImport } from './routes/app.pharmacies'
import { Route as AppPrescriptionsRouteImport } from './routes/app.prescriptions'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTriageRouteImport } from './routes/app.triage'
import { Route as AppVerifyRouteImport } from './routes/app.verify'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor.analytics'
import { Route as DoctorCdssRouteImport } from './routes/doctor.cdss'
import { Route as DoctorConsultsRouteImport } from './routes/doctor.consults'
import { Route as DoctorLabsRouteImport } from './routes/doctor.labs'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as PharmacyAnalyticsRouteImport } from './routes/pharmacy.analytics'
import { Route as PharmacyCustomersRouteImport } from './routes/pharmacy.customers'
import { Route as PharmacyInventoryRouteImport } from './routes/pharmacy.inventory'
import { Route as PharmacyOrdersRouteImport } from './routes/pharmacy.orders'
import { Route as PharmacyPrescriptionsRouteImport } from './routes/pharmacy.prescriptions'
import { Route as PharmacySuppliersRouteImport } from './routes/pharmacy.suppliers'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppMedicineMedicineIdRouteImport } from './routes/app.medicine.$medicineId'
import { Route as AppPharmaciesIndexRouteImport } from './routes/app.pharmacies.index'
import { Route as AppPharmaciesPharmacyIdRouteImport } from './routes/app.pharmacies.$pharmacyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchRoute = SwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPharmaciesRoute = AdminPharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiScanBottleRoute = ApiScanBottleRouteImport.update({
  id: '/api/scan-bottle',
  path: '/api/scan-bottle',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppInteractionsRoute = AppInteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsRoute = AppLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmaciesRoute = AppPharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorCdssRoute = DoctorCdssRouteImport.update({
  id: '/cdss',
  path: '/cdss',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorConsultsRoute = DoctorConsultsRouteImport.update({
  id: '/consults',
  path: '/consults',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorLabsRoute = DoctorLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyAnalyticsRoute = PharmacyAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyCustomersRoute = PharmacyCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyInventoryRoute = PharmacyInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyOrdersRoute = PharmacyOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyPrescriptionsRoute = PharmacyPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacySuppliersRoute = PharmacySuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => PharmacyRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppMedicineMedicineIdRoute = AppMedicineMedicineIdRouteImport.update({
  id: '/medicine/$medicineId',
  path: '/medicine/$medicineId',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmaciesIndexRoute = AppPharmaciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPharmaciesRoute,
} as any)
const AppPharmaciesPharmacyIdRoute = AppPharmaciesPharmacyIdRouteImport.update({
  id: '/$pharmacyId',
  path: '/$pharmacyId',
  getParentRoute: () => AppPharmaciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/emergency': typeof EmergencyRoute
  '/mcp': typeof McpRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/switch': typeof SwitchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/scan-bottle': typeof ApiScanBottleRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/cart': typeof AppCartRoute
  '/app/compare': typeof AppCompareRoute
  '/app/history': typeof AppHistoryRoute
  '/app/interactions': typeof AppInteractionsRoute
  '/app/labs': typeof AppLabsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pharmacies': typeof AppPharmaciesRouteWithChildren
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/triage': typeof AppTriageRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/cdss': typeof DoctorCdssRoute
  '/doctor/consults': typeof DoctorConsultsRoute
  '/doctor/labs': typeof DoctorLabsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/pharmacy/analytics': typeof PharmacyAnalyticsRoute
  '/pharmacy/customers': typeof PharmacyCustomersRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/orders': typeof PharmacyOrdersRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/pharmacy/suppliers': typeof PharmacySuppliersRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/medicine/$medicineId': typeof AppMedicineMedicineIdRoute
  '/app/pharmacies/$pharmacyId': typeof AppPharmaciesPharmacyIdRoute
  '/app/pharmacies/': typeof AppPharmaciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/switch': typeof SwitchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/scan-bottle': typeof ApiScanBottleRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/cart': typeof AppCartRoute
  '/app/compare': typeof AppCompareRoute
  '/app/history': typeof AppHistoryRoute
  '/app/interactions': typeof AppInteractionsRoute
  '/app/labs': typeof AppLabsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/triage': typeof AppTriageRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/cdss': typeof DoctorCdssRoute
  '/doctor/consults': typeof DoctorConsultsRoute
  '/doctor/labs': typeof DoctorLabsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/pharmacy/analytics': typeof PharmacyAnalyticsRoute
  '/pharmacy/customers': typeof PharmacyCustomersRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/orders': typeof PharmacyOrdersRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/pharmacy/suppliers': typeof PharmacySuppliersRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/medicine/$medicineId': typeof AppMedicineMedicineIdRoute
  '/app/pharmacies/$pharmacyId': typeof AppPharmaciesPharmacyIdRoute
  '/app/pharmacies': typeof AppPharmaciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/emergency': typeof EmergencyRoute
  '/mcp': typeof McpRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/switch': typeof SwitchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/pharmacies': typeof AdminPharmaciesRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/scan-bottle': typeof ApiScanBottleRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/cart': typeof AppCartRoute
  '/app/compare': typeof AppCompareRoute
  '/app/history': typeof AppHistoryRoute
  '/app/interactions': typeof AppInteractionsRoute
  '/app/labs': typeof AppLabsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pharmacies': typeof AppPharmaciesRouteWithChildren
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/triage': typeof AppTriageRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/cdss': typeof DoctorCdssRoute
  '/doctor/consults': typeof DoctorConsultsRoute
  '/doctor/labs': typeof DoctorLabsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/pharmacy/analytics': typeof PharmacyAnalyticsRoute
  '/pharmacy/customers': typeof PharmacyCustomersRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/orders': typeof PharmacyOrdersRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/pharmacy/suppliers': typeof PharmacySuppliersRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/medicine/$medicineId': typeof AppMedicineMedicineIdRoute
  '/app/pharmacies/$pharmacyId': typeof AppPharmaciesPharmacyIdRoute
  '/app/pharmacies/': typeof AppPharmaciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/doctor'
    | '/emergency'
    | '/mcp'
    | '/pharmacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/switch'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/moderation'
    | '/admin/pharmacies'
    | '/admin/revenue'
    | '/admin/system'
    | '/admin/users'
    | '/api/scan-bottle'
    | '/app/assistant'
    | '/app/cart'
    | '/app/compare'
    | '/app/history'
    | '/app/interactions'
    | '/app/labs'
    | '/app/notifications'
    | '/app/orders'
    | '/app/pharmacies'
    | '/app/prescriptions'
    | '/app/reminders'
    | '/app/search'
    | '/app/settings'
    | '/app/triage'
    | '/app/verify'
    | '/app/workspace'
    | '/doctor/analytics'
    | '/doctor/cdss'
    | '/doctor/consults'
    | '/doctor/labs'
    | '/doctor/prescriptions'
    | '/doctor/schedule'
    | '/pharmacy/analytics'
    | '/pharmacy/customers'
    | '/pharmacy/inventory'
    | '/pharmacy/orders'
    | '/pharmacy/prescriptions'
    | '/pharmacy/suppliers'
    | '/admin/'
    | '/app/'
    | '/doctor/'
    | '/pharmacy/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/medicine/$medicineId'
    | '/app/pharmacies/$pharmacyId'
    | '/app/pharmacies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/emergency'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/switch'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/moderation'
    | '/admin/pharmacies'
    | '/admin/revenue'
    | '/admin/system'
    | '/admin/users'
    | '/api/scan-bottle'
    | '/app/assistant'
    | '/app/cart'
    | '/app/compare'
    | '/app/history'
    | '/app/interactions'
    | '/app/labs'
    | '/app/notifications'
    | '/app/orders'
    | '/app/prescriptions'
    | '/app/reminders'
    | '/app/search'
    | '/app/settings'
    | '/app/triage'
    | '/app/verify'
    | '/app/workspace'
    | '/doctor/analytics'
    | '/doctor/cdss'
    | '/doctor/consults'
    | '/doctor/labs'
    | '/doctor/prescriptions'
    | '/doctor/schedule'
    | '/pharmacy/analytics'
    | '/pharmacy/customers'
    | '/pharmacy/inventory'
    | '/pharmacy/orders'
    | '/pharmacy/prescriptions'
    | '/pharmacy/suppliers'
    | '/admin'
    | '/app'
    | '/doctor'
    | '/pharmacy'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/medicine/$medicineId'
    | '/app/pharmacies/$pharmacyId'
    | '/app/pharmacies'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/doctor'
    | '/emergency'
    | '/mcp'
    | '/pharmacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/switch'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/moderation'
    | '/admin/pharmacies'
    | '/admin/revenue'
    | '/admin/system'
    | '/admin/users'
    | '/api/scan-bottle'
    | '/app/assistant'
    | '/app/cart'
    | '/app/compare'
    | '/app/history'
    | '/app/interactions'
    | '/app/labs'
    | '/app/notifications'
    | '/app/orders'
    | '/app/pharmacies'
    | '/app/prescriptions'
    | '/app/reminders'
    | '/app/search'
    | '/app/settings'
    | '/app/triage'
    | '/app/verify'
    | '/app/workspace'
    | '/doctor/analytics'
    | '/doctor/cdss'
    | '/doctor/consults'
    | '/doctor/labs'
    | '/doctor/prescriptions'
    | '/doctor/schedule'
    | '/pharmacy/analytics'
    | '/pharmacy/customers'
    | '/pharmacy/inventory'
    | '/pharmacy/orders'
    | '/pharmacy/prescriptions'
    | '/pharmacy/suppliers'
    | '/admin/'
    | '/app/'
    | '/doctor/'
    | '/pharmacy/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/medicine/$medicineId'
    | '/app/pharmacies/$pharmacyId'
    | '/app/pharmacies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  EmergencyRoute: typeof EmergencyRoute
  McpRoute: typeof McpRoute
  PharmacyRoute: typeof PharmacyRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwitchRoute: typeof SwitchRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiScanBottleRoute: typeof ApiScanBottleRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch': {
      id: '/switch'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof SwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pharmacies': {
      id: '/admin/pharmacies'
      path: '/pharmacies'
      fullPath: '/admin/pharmacies'
      preLoaderRoute: typeof AdminPharmaciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/scan-bottle': {
      id: '/api/scan-bottle'
      path: '/api/scan-bottle'
      fullPath: '/api/scan-bottle'
      preLoaderRoute: typeof ApiScanBottleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interactions': {
      id: '/app/interactions'
      path: '/interactions'
      fullPath: '/app/interactions'
      preLoaderRoute: typeof AppInteractionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/labs': {
      id: '/app/labs'
      path: '/labs'
      fullPath: '/app/labs'
      preLoaderRoute: typeof AppLabsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacies': {
      id: '/app/pharmacies'
      path: '/pharmacies'
      fullPath: '/app/pharmacies'
      preLoaderRoute: typeof AppPharmaciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prescriptions': {
      id: '/app/prescriptions'
      path: '/prescriptions'
      fullPath: '/app/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/triage': {
      id: '/app/triage'
      path: '/triage'
      fullPath: '/app/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/cdss': {
      id: '/doctor/cdss'
      path: '/cdss'
      fullPath: '/doctor/cdss'
      preLoaderRoute: typeof DoctorCdssRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/consults': {
      id: '/doctor/consults'
      path: '/consults'
      fullPath: '/doctor/consults'
      preLoaderRoute: typeof DoctorConsultsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/labs': {
      id: '/doctor/labs'
      path: '/labs'
      fullPath: '/doctor/labs'
      preLoaderRoute: typeof DoctorLabsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/analytics': {
      id: '/pharmacy/analytics'
      path: '/analytics'
      fullPath: '/pharmacy/analytics'
      preLoaderRoute: typeof PharmacyAnalyticsRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/customers': {
      id: '/pharmacy/customers'
      path: '/customers'
      fullPath: '/pharmacy/customers'
      preLoaderRoute: typeof PharmacyCustomersRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/inventory': {
      id: '/pharmacy/inventory'
      path: '/inventory'
      fullPath: '/pharmacy/inventory'
      preLoaderRoute: typeof PharmacyInventoryRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/orders': {
      id: '/pharmacy/orders'
      path: '/orders'
      fullPath: '/pharmacy/orders'
      preLoaderRoute: typeof PharmacyOrdersRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/prescriptions': {
      id: '/pharmacy/prescriptions'
      path: '/prescriptions'
      fullPath: '/pharmacy/prescriptions'
      preLoaderRoute: typeof PharmacyPrescriptionsRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/suppliers': {
      id: '/pharmacy/suppliers'
      path: '/suppliers'
      fullPath: '/pharmacy/suppliers'
      preLoaderRoute: typeof PharmacySuppliersRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/medicine/$medicineId': {
      id: '/app/medicine/$medicineId'
      path: '/medicine/$medicineId'
      fullPath: '/app/medicine/$medicineId'
      preLoaderRoute: typeof AppMedicineMedicineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pharmacies/': {
      id: '/app/pharmacies/'
      path: '/'
      fullPath: '/app/pharmacies/'
      preLoaderRoute: typeof AppPharmaciesIndexRouteImport
      parentRoute: typeof AppPharmaciesRoute
    }
    '/app/pharmacies/$pharmacyId': {
      id: '/app/pharmacies/$pharmacyId'
      path: '/$pharmacyId'
      fullPath: '/app/pharmacies/$pharmacyId'
      preLoaderRoute: typeof AppPharmaciesPharmacyIdRouteImport
      parentRoute: typeof AppPharmaciesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPharmaciesRoute: typeof AdminPharmaciesRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPharmaciesRoute: AdminPharmaciesRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppPharmaciesRouteChildren {
  AppPharmaciesPharmacyIdRoute: typeof AppPharmaciesPharmacyIdRoute
  AppPharmaciesIndexRoute: typeof AppPharmaciesIndexRoute
}

const AppPharmaciesRouteChildren: AppPharmaciesRouteChildren = {
  AppPharmaciesPharmacyIdRoute: AppPharmaciesPharmacyIdRoute,
  AppPharmaciesIndexRoute: AppPharmaciesIndexRoute,
}

const AppPharmaciesRouteWithChildren = AppPharmaciesRoute._addFileChildren(
  AppPharmaciesRouteChildren,
)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCartRoute: typeof AppCartRoute
  AppCompareRoute: typeof AppCompareRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInteractionsRoute: typeof AppInteractionsRoute
  AppLabsRoute: typeof AppLabsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPharmaciesRoute: typeof AppPharmaciesRouteWithChildren
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTriageRoute: typeof AppTriageRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMedicineMedicineIdRoute: typeof AppMedicineMedicineIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCartRoute: AppCartRoute,
  AppCompareRoute: AppCompareRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInteractionsRoute: AppInteractionsRoute,
  AppLabsRoute: AppLabsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPharmaciesRoute: AppPharmaciesRouteWithChildren,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTriageRoute: AppTriageRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
  AppMedicineMedicineIdRoute: AppMedicineMedicineIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DoctorRouteChildren {
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorCdssRoute: typeof DoctorCdssRoute
  DoctorConsultsRoute: typeof DoctorConsultsRoute
  DoctorLabsRoute: typeof DoctorLabsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorCdssRoute: DoctorCdssRoute,
  DoctorConsultsRoute: DoctorConsultsRoute,
  DoctorLabsRoute: DoctorLabsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PharmacyRouteChildren {
  PharmacyAnalyticsRoute: typeof PharmacyAnalyticsRoute
  PharmacyCustomersRoute: typeof PharmacyCustomersRoute
  PharmacyInventoryRoute: typeof PharmacyInventoryRoute
  PharmacyOrdersRoute: typeof PharmacyOrdersRoute
  PharmacyPrescriptionsRoute: typeof PharmacyPrescriptionsRoute
  PharmacySuppliersRoute: typeof PharmacySuppliersRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
}

const PharmacyRouteChildren: PharmacyRouteChildren = {
  PharmacyAnalyticsRoute: PharmacyAnalyticsRoute,
  PharmacyCustomersRoute: PharmacyCustomersRoute,
  PharmacyInventoryRoute: PharmacyInventoryRoute,
  PharmacyOrdersRoute: PharmacyOrdersRoute,
  PharmacyPrescriptionsRoute: PharmacyPrescriptionsRoute,
  PharmacySuppliersRoute: PharmacySuppliersRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
}

const PharmacyRouteWithChildren = PharmacyRoute._addFileChildren(
  PharmacyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DoctorRoute: DoctorRouteWithChildren,
  EmergencyRoute: EmergencyRoute,
  McpRoute: McpRoute,
  PharmacyRoute: PharmacyRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwitchRoute: SwitchRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiScanBottleRoute: ApiScanBottleRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
